feat(component): added nakiacallaway.js
Alexg1021/testing-gitflow pull request #20
Opened 2021-03-15 21:37 UTC by nakiacallaway

Closes issue #14

2021-03-15 21:42 UTC, Alexg1021 requested changes

2021-03-15 21:42 UTC, Alexg1021 commented on src/nakiacallaway.js
> +const nikName = () => {
React Components require Pascal casing (i.e.) Capital first letter

2021-03-15 21:47 UTC, nakiacallaway commented on src/nakiacallaway.js
> +const nikName = () => {
Corrected camel casing, removed extraneous code.

2021-03-22 17:52 UTC, Alexg1021 approved these changes
LGTM! 🚀

2021-03-22 17:52 UTC, merged